#!/usr/bin/env python3
"""
KPI Anomaly Detection: TS2Vec vs TS2Vec-MSM Comparison

This script provides a comprehensive evaluation of TS2Vec baseline vs TS2Vec-MSM hybrid 
for anomaly detection on the KPI dataset. It implements the paper's methodology of comparing
masked vs unmasked representations to detect anomalies.

Requirements:
1. KPI dataset files: phase2_train.csv, phase2_ground_truth.hdf
2. Preprocessed kpi.pkl (generated by running: python datasets/preprocess_kpi.py)
3. Trained models (generated by running scripts/kpi.sh)

Usage:
    python kpi_anomaly_comparison.py --data-path kpi.pkl --baseline-model [path] --msm-model [path]
"""

import os
import sys
import argparse
import pickle
import numpy as np
import time
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent
sys.path.append(str(project_root))

import torch
from ts2vec import TS2Vec
from ts2vec_msm import TS2VecMSM
from tasks.anomaly_detection import eval_anomaly_detection, eval_anomaly_detection_coldstart

def setup_gpu():
    """Configure GPU settings for optimal performance"""
    if torch.cuda.is_available():
        device = 'cuda'
        print(f"🚀 Using GPU: {torch.cuda.get_device_name()}")
        print(f"💾 GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
        
        # Optimize GPU settings
        torch.backends.cudnn.benchmark = True
        torch.cuda.empty_cache()
    else:
        device = 'cpu'
        print("🖥️  Using CPU (GPU not available)")
    
    return device

def load_kpi_data(data_path):
    """Load preprocessed KPI dataset"""
    print(f"📂 Loading KPI dataset from: {data_path}")
    
    if not os.path.exists(data_path):
        print(f"❌ Error: KPI dataset not found at {data_path}")
        print("\n📋 To prepare the KPI dataset:")
        print("1. Download phase2_train.csv and phase2_ground_truth.hdf from KPI dataset")
        print("2. Place them in the datasets/ directory")
        print("3. Run: python datasets/preprocess_kpi.py")
        print("4. This will generate kpi.pkl")
        return None
    
    try:
        with open(data_path, 'rb') as f:
            data = pickle.load(f)
        
        train_data = data['train_data']
        train_labels = data['train_labels'] 
        train_timestamps = data['train_timestamps']
        test_data = data['test_data']
        test_labels = data['test_labels']
        test_timestamps = data['test_timestamps']
        
        print(f"✅ KPI dataset loaded successfully!")
        print(f"📊 Train series: {len(train_data)}")
        print(f"📊 Test series: {len(test_data)}")
        
        # Print detailed statistics
        total_train_points = sum(len(series) for series in train_data.values())
        total_test_points = sum(len(series) for series in test_data.values())
        total_anomalies = sum(labels.sum() for labels in test_labels.values())
        
        print(f"📈 Total train points: {total_train_points:,}")
        print(f"📈 Total test points: {total_test_points:,}")
        print(f"🚨 Total anomalies: {total_anomalies:,} ({100*total_anomalies/total_test_points:.2f}%)")
        
        return {
            'train_data': train_data,
            'train_labels': train_labels,
            'train_timestamps': train_timestamps,
            'test_data': test_data, 
            'test_labels': test_labels,
            'test_timestamps': test_timestamps
        }
        
    except Exception as e:
        print(f"❌ Error loading KPI dataset: {e}")
        return None

def load_model(model_path, model_type='baseline', device='cuda'):
    """Load trained TS2Vec or TS2Vec-MSM model"""
    print(f"🤖 Loading {model_type} model from: {model_path}")
    
    if not os.path.exists(model_path):
        print(f"❌ Error: Model not found at {model_path}")
        print("\n📋 To train models:")
        print("1. For baseline TS2Vec: python train.py kpi anomaly_0 --loader anomaly --repr-dims 320 --eval")
        print("2. For TS2Vec-MSM: python train.py kpi anomaly_0 --loader anomaly --repr-dims 320 --eval --msm")
        return None
    
    try:
        if model_type == 'baseline':
            model = TS2Vec(
                input_dims=1,
                device=device,
                output_dims=320
            )
        else:  # MSM
            model = TS2VecMSM(
                input_dims=1,
                device=device,
                output_dims=320,
                mask_mode='binomial',
                mask_rate=0.1,
                lm=3.0,
                msm_weight=0.1
            )
        
        model.load(model_path)
        print(f"✅ {model_type} model loaded successfully!")
        return model
        
    except Exception as e:
        print(f"❌ Error loading {model_type} model: {e}")
        return None

def run_anomaly_detection_comparison(data, baseline_model, msm_model, delay=7):
    """Compare baseline TS2Vec vs TS2Vec-MSM for anomaly detection"""
    
    print("\n" + "="*80)
    print("🎯 ANOMALY DETECTION COMPARISON: TS2Vec vs TS2Vec-MSM")
    print("="*80)
    
    results = {}
    
    # Extract data
    train_data = data['train_data']
    train_labels = data['train_labels']
    train_timestamps = data['train_timestamps']
    test_data = data['test_data']
    test_labels = data['test_labels']
    test_timestamps = data['test_timestamps']
    
    # Test baseline TS2Vec
    if baseline_model is not None:
        print("\n🔬 TESTING BASELINE TS2Vec")
        print("-" * 50)
        start_time = time.time()
        
        try:
            _, baseline_results = eval_anomaly_detection(
                baseline_model, 
                train_data, train_labels, train_timestamps,
                test_data, test_labels, test_timestamps,
                delay=delay
            )
            
            baseline_results['model_type'] = 'TS2Vec Baseline'
            results['baseline'] = baseline_results
            
            print(f"\n✅ BASELINE TS2Vec RESULTS:")
            print(f"   🎯 F1 Score: {baseline_results['f1']:.4f}")
            print(f"   🎯 Precision: {baseline_results['precision']:.4f}")
            print(f"   🎯 Recall: {baseline_results['recall']:.4f}")
            print(f"   ⏱️ Time: {baseline_results['infer_time']:.2f}s")
            
        except Exception as e:
            print(f"❌ Error testing baseline model: {e}")
            results['baseline'] = None
    
    # Test TS2Vec-MSM
    if msm_model is not None:
        print("\n🔬 TESTING TS2Vec-MSM HYBRID")
        print("-" * 50)
        start_time = time.time()
        
        try:
            _, msm_results = eval_anomaly_detection(
                msm_model,
                train_data, train_labels, train_timestamps, 
                test_data, test_labels, test_timestamps,
                delay=delay
            )
            
            msm_results['model_type'] = 'TS2Vec-MSM Hybrid'
            results['msm'] = msm_results
            
            print(f"\n✅ TS2Vec-MSM RESULTS:")
            print(f"   🎯 F1 Score: {msm_results['f1']:.4f}")
            print(f"   🎯 Precision: {msm_results['precision']:.4f}")
            print(f"   🎯 Recall: {msm_results['recall']:.4f}")
            print(f"   ⏱️ Time: {msm_results['infer_time']:.2f}s")
            
        except Exception as e:
            print(f"❌ Error testing MSM model: {e}")
            results['msm'] = None
    
    return results

def analyze_results(results):
    """Analyze and compare results between models"""
    
    print("\n" + "="*80)
    print("📊 COMPREHENSIVE ANALYSIS")
    print("="*80)
    
    if 'baseline' in results and 'msm' in results and results['baseline'] and results['msm']:
        baseline = results['baseline']
        msm = results['msm']
        
        print("\n📈 PERFORMANCE COMPARISON:")
        print("-" * 40)
        
        metrics = ['f1', 'precision', 'recall']
        improvements = {}
        
        for metric in metrics:
            baseline_val = baseline[metric]
            msm_val = msm[metric]
            improvement = ((msm_val - baseline_val) / baseline_val) * 100
            improvements[metric] = improvement
            
            status = "🟢" if improvement > 0 else "🔴" if improvement < -1 else "🟡"
            print(f"   {metric.capitalize():10}: {baseline_val:.4f} → {msm_val:.4f} ({improvement:+.1f}%) {status}")
        
        # Overall assessment
        print(f"\n📋 SUMMARY:")
        print("-" * 40)
        
        avg_improvement = np.mean(list(improvements.values()))
        if avg_improvement > 5:
            assessment = "🎉 TS2Vec-MSM shows SIGNIFICANT improvement for anomaly detection!"
        elif avg_improvement > 0:
            assessment = "✅ TS2Vec-MSM shows modest improvement for anomaly detection"
        elif avg_improvement > -5:
            assessment = "🤔 TS2Vec-MSM shows comparable performance to baseline"
        else:
            assessment = "❌ TS2Vec-MSM underperforms baseline for anomaly detection"
            
        print(f"   {assessment}")
        print(f"   📊 Average improvement: {avg_improvement:+.1f}%")
        
        # Time comparison
        time_ratio = msm['infer_time'] / baseline['infer_time']
        print(f"   ⏱️ Time overhead: {time_ratio:.1f}x")
        
        return {
            'improvements': improvements,
            'avg_improvement': avg_improvement,
            'time_ratio': time_ratio,
            'assessment': assessment
        }
    
    else:
        print("⚠️ Cannot compare - missing model results")
        return None

def main():
    parser = argparse.ArgumentParser(description='KPI Anomaly Detection: TS2Vec vs TS2Vec-MSM')
    parser.add_argument('--data-path', default='kpi.pkl', help='Path to preprocessed KPI dataset')
    parser.add_argument('--baseline-model', help='Path to trained baseline TS2Vec model')
    parser.add_argument('--msm-model', help='Path to trained TS2Vec-MSM model')
    parser.add_argument('--delay', type=int, default=7, help='Delay threshold for anomaly detection')
    parser.add_argument('--output', help='Output file for results (optional)')
    
    args = parser.parse_args()
    
    print("🚀 KPI ANOMALY DETECTION COMPARISON")
    print("=" * 50)
    
    # Setup
    device = setup_gpu()
    
    # Load data
    data = load_kpi_data(args.data_path)
    if data is None:
        return
    
    # Load models
    baseline_model = None
    msm_model = None
    
    if args.baseline_model:
        baseline_model = load_model(args.baseline_model, 'baseline', device)
    
    if args.msm_model:
        msm_model = load_model(args.msm_model, 'msm', device)
    
    if baseline_model is None and msm_model is None:
        print("❌ No valid models provided. Please specify --baseline-model and/or --msm-model")
        return
    
    # Run comparison
    results = run_anomaly_detection_comparison(data, baseline_model, msm_model, args.delay)
    
    # Analyze results
    analysis = analyze_results(results)
    
    # Save results if requested
    if args.output:
        output_data = {
            'results': results,
            'analysis': analysis,
            'config': {
                'data_path': args.data_path,
                'delay': args.delay,
                'timestamp': time.time()
            }
        }
        
        with open(args.output, 'wb') as f:
            pickle.dump(output_data, f)
        print(f"\n💾 Results saved to: {args.output}")
    
    print(f"\n🏁 Evaluation completed!")

if __name__ == "__main__":
    main()